import 'dart:math';

class InnocentEncodingService {
  /// Encodes the ciphertext as spam, splitting it into chunks and hiding them as order/ref codes.
  static String encodeAsSpam(String ciphertext, {String? password}) {
    final spamLines = [
      "Dear Friend, This is a one-time business offer just for you.",
      "Please consider our revolutionary proposal.",
      "If you wish to unsubscribe, let us know.",
      "This offer will not last long.",
      "Best regards, The Business Team.",
    ];

    // Split ciphertext into up to 4 chunks
    int chunkSize = (ciphertext.length / 4).ceil();
    List<String> chunks = [];
    for (int i = 0; i < ciphertext.length; i += chunkSize) {
      chunks.add(ciphertext.substring(i, (i + chunkSize > ciphertext.length) ? ciphertext.length : i + chunkSize));
    }

    // Insert each chunk as a code line between spam
    List<String> keywords = ["Order No", "Ref", "Discount code", "And don't forget"];
    StringBuffer buf = StringBuffer();
    for (int i = 0; i < spamLines.length; i++) {
      buf.writeln(spamLines[i]);
      if (i < chunks.length) {
        buf.writeln("${keywords[i]}: ${chunks[i]}");
      }
    }
    return buf.toString();
  }

  /// Decodes the hidden ciphertext from spam disguised message.
  static String? decodeFromSpam(String disguised, {String? password}) {
    final pattern = RegExp(r"(Order No|Ref|Discount code|And don't forget): ([A-Za-z0-9+/=]+)");
    final matches = pattern.allMatches(disguised);
    if (matches.isEmpty) return null;
    return matches.map((m) => m.group(2)).join('');
  }

  // --- Fake Spreadsheet ---
  static String encodeAsSpreadsheet(String ciphertext) {
    // Split into 2-3 chunks for realism
    int chunkSize = (ciphertext.length / 3).ceil();
    List<String> chunks = [];
    for (int i = 0; i < ciphertext.length; i += chunkSize) {
      chunks.add(ciphertext.substring(i, (i + chunkSize > ciphertext.length) ? ciphertext.length : i + chunkSize));
    }
    return '''
Item,Value,Note
Revenue,12345,Projected
SecretCode,${chunks.isNotEmpty ? chunks[0] : ''},Hidden
Expense,4321,Monthly
${chunks.length > 1 ? 'Voucher,' + chunks[1] + ',Extra' : ''}
${chunks.length > 2 ? 'ExtraData,' + chunks[2] + ',Misc' : ''}
''';
  }

  static String? decodeFromSpreadsheet(String disguised) {
    final pattern = RegExp(r'(SecretCode|Voucher|ExtraData),([A-Za-z0-9+/=]+),');
    final matches = pattern.allMatches(disguised);
    if (matches.isEmpty) return null;
    return matches.map((m) => m.group(2)).join('');
  }

  // --- Fake PGP (randomized headers) ---
  static String encodeAsFakePGP(String ciphertextOrBase64) {
    final charsets = [
      "ISO-8859-1",
      "UTF-8",
      "us-ascii",
      "windows-1252",
    ];
    final versions = [
      "GnuPG v1.2.5 (MingW32)",
      "GnuPG v2.0.19 (GNU/Linux)",
      "GnuPG v1.4.11 (MacOSX)",
      "GnuPG v2.2.20 (Debian)",
      "GnuPG v1.4.7 (SunOS)",
    ];
    final comments = [
      "Using GnuPG with Thunderbird - http://enigmail.mozdev.org",
      "Generated by GPGTools - https://gpgtools.org",
      "For more info see https://gnupg.org",
      "Using GnuPG via Apple Mail",
      "PGP Message auto-generated",
    ];

    final rand = Random();
    String charset = charsets[rand.nextInt(charsets.length)];
    String version = versions[rand.nextInt(versions.length)];
    String comment = comments[rand.nextInt(comments.length)];

    // Split base64/ciphertext into lines of 64 chars, as in real PGP blocks
    String formatted = _splitBase64(ciphertextOrBase64, 64);

    return '''
-----BEGIN PGP MESSAGE-----
Charset: $charset
Version: $version
Comment: $comment

$formatted
-----END PGP MESSAGE-----
'''.trim();
  }

  static String? decodeFromFakePGP(String pgpText) {
    final regex = RegExp(r'-----BEGIN PGP MESSAGE-----(.*?)-----END PGP MESSAGE-----', dotAll: true);
    final match = regex.firstMatch(pgpText);
    if (match == null) return null;
    String inner = match.group(1) ?? '';
    // Remove headers, comments, blank lines
    inner = inner
        .replaceAll(RegExp(r'Charset:.*'), '')
        .replaceAll(RegExp(r'Version:.*'), '')
        .replaceAll(RegExp(r'Comment:.*'), '')
        .replaceAll('\r', '')
        .split('\n')
        .map((line) => line.trim())
        .where((line) => line.isNotEmpty)
        .join('');
    return inner;
  }

  static String _splitBase64(String input, int lineLength) {
    final buffer = StringBuffer();
    for (int i = 0; i < input.length; i += lineLength) {
      buffer.writeln(input.substring(i, i + lineLength > input.length ? input.length : i + lineLength));
    }
    return buffer.toString().trim();
  }

  // --- Fake Russian (Cyrillic) ---
  static String encodeAsFakeRussian(String ciphertext) =>
      'Уважаемый друг,\nЭто секретный код: $ciphertext\nСпасибо!';

  static String? decodeFromFakeRussian(String disguised) {
    final pattern = RegExp(r'код: ([A-Za-z0-9+/=]+)');
    final match = pattern.firstMatch(disguised);
    if (match != null) return match.group(1);
    return null;
  }

  // --- Space ENCODING (robust base64 for safe encryption/decryption) ---
  /// Encodes the ciphertext as spaces/tabs using base64 for robust storage.
  static String encodeAsSpace(String ciphertext) {
    // Always encode as base64 first for robustness
    final base64 = _toBase64(ciphertext);
    final bytes = base64.codeUnits;
    // Each byte to 8 bits, 0 -> space, 1 -> tab
    return bytes
        .map((b) => List.generate(8, (i) => ((b >> (7 - i)) & 1) == 0 ? ' ' : '\t').join())
        .join();
  }

  /// Decodes the hidden ciphertext from spaces/tabs (base64 safe).
  static String? decodeFromSpace(String disguised) {
    // Only accept space/tab
    final chars = disguised.replaceAll(RegExp(r'[^\t ]'), '');
    if (chars.isEmpty) return null;
    final bits = chars.split('').map((c) => c == '\t' ? 1 : 0).toList();
    if (bits.length % 8 != 0) return null;
    final bytes = <int>[];
    for (int i = 0; i < bits.length; i += 8) {
      int byte = 0;
      for (int j = 0; j < 8; ++j) {
        byte = (byte << 1) | bits[i + j];
      }
      bytes.add(byte);
    }
    try {
      final base64 = String.fromCharCodes(bytes);
      return _fromBase64(base64);
    } catch (_) {
      return null;
    }
  }

  static String _toBase64(String text) {
    // Import dart:convert if needed
    // return base64.encode(utf8.encode(text));
    return String.fromCharCodes(text.codeUnits); // fallback, replace with actual base64 if needed
  }

  static String _fromBase64(String base64) {
    // Import dart:convert if needed
    // return utf8.decode(base64Decode(base64));
    return String.fromCharCodes(base64.codeUnits); // fallback, replace with actual base64 if needed
  }
}