// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB5lcD3jindwA1H4_Bao6ED5ZuMSxN4bo',
    appId: '1:76800991751:web:eb9a35d5e2c3f9c3a380a2',
    messagingSenderId: '76800991751',
    projectId: 'sccapp-c3165',
    authDomain: 'sccapp-c3165.firebaseapp.com',
    storageBucket: "sccapp-c3165.appspot.com",
    measurementId: 'G-CEGQ06WT91',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5uwPZ8Z0a6pncKbRjeKcfqrBNouMaAjY',
    appId: '1:76800991751:android:8ad040615917a6c4a380a2',
    messagingSenderId: '76800991751',
    projectId: 'sccapp-c3165',
    storageBucket: "sccapp-c3165.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDYa0QJVWMHtjP10fyWNk-qWptlG7VX3o',
    appId: '1:76800991751:ios:e0157025f15cf20da380a2',
    messagingSenderId: '76800991751',
    projectId: 'sccapp-c3165',
    storageBucket: "sccapp-c3165.appspot.com",
    iosClientId: '76800991751-3g9ctbnngghe0vjcsgafrkd8tqhsf9v8.apps.googleusercontent.com',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDYa0QJVWMHtjP10fyWNk-qWptlG7VX3o',
    appId: '1:76800991751:ios:e0157025f15cf20da380a2',
    messagingSenderId: '76800991751',
    projectId: 'sccapp-c3165',
    storageBucket: "sccapp-c3165.appspot.com",
    iosClientId: '76800991751-3g9ctbnngghe0vjcsgafrkd8tqhsf9v8.apps.googleusercontent.com',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB5lcD3jindwA1H4_Bao6ED5ZuMSxN4bo',
    appId: '1:76800991751:web:d5b689455c8a51d5a380a2',
    messagingSenderId: '76800991751',
    projectId: 'sccapp-c3165',
    authDomain: 'sccapp-c3165.firebaseapp.com',
    storageBucket: "sccapp-c3165.appspot.com",
    measurementId: 'G-8ZDHRPDSC8',
  );
}
